apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-v3
spec:
  selector:
    matchLabels:
      app: docs-v3
  replicas: 1
  template:
    metadata:
      labels:
        app: docs-v3
    spec:
      containers:
        - name: docs-v3
          image: docs-v3
          ports:
            - containerPort: 8000
